diyaChat/chatroom/urls.py
from django.urls import path
from . import views

from django.conf.urls import url

app_name = 'chatroom'
urlpatterns = [
   # ex) /chatroom/
   path('', views.index, name='index'),

   # ex) /chatroom/bert/
   path('<str:lm_name>/', views.room, name='room'),

   #path('<str:lm_name>/<str:num>/', views.helloworld, name='helloworld'),
   path('<str:lm_name>/<str:message>/', views.message, name='message'),

   # ex) /chatroom/newDataset
   path('<str:lm_name>/ajax/post_dataset/', views.post_dataset, name='post_dataset'),
]

diyaChat/diyaChat/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('chatroom/', include('chatroom.urls')),
    path('admin/', admin.site.urls),

]

diyaChat/chatroom/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    date_time = models.DateTimeField(' question date time')

    def __str__(self):
        return self.question_text

    def was_entered_recently(self):
        return self.date_time >= timezone.now() - datetime.timedelta(days=1)

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    date_time = models.DateTimeField(' answer date time')

    def __str__(self):
        return self.answer_text

    def was_entered_recently(self):
        return self.date_time >= timezone.now() - datetime.timedelta(days=1)

class Room(models.Model):
    # ex) seq2seq, transformer, BERT
    # @TODO: epoch과 accuracy 추가할 것
    lm_name = models.CharField(max_length=20)    # the chatbot language model adopted to chatroom
    subtitle = models.CharField(max_length=80)
    description = models.CharField(max_length=200)
    paper_link = models.CharField(max_length=200)
    rank = models.IntegerField(default=0)
    loss = models.FloatField(default=0)

    def __str__(self):
        return self.lm_name

class UserInputDataset(models.Model):
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)

    def __str__(self):
        return self.question + " || "  + self.answer

diyaChat/chatroom/forms.py
from django import forms
from .models import UserInputDataset

class DatasetPostForm(forms.ModelForm):

    class Meta:
        model = UserInputDataset
        fields = ('question', 'answer',)

diyaChat/chatroom/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.views.generic.edit import CreateView
from django.views.decorators.csrf import csrf_exempt

from .models import Room
from .models import UserInputDataset

from .forms import DatasetPostForm

import json

import random
import tensorflow as tf
import os
import sys


###### import for transformer model inferencing ######
from .transformer import data as tranformer_data
from .transformer import model as transformer
from .transformer.configs import DEFINES as DEFINES_transformer

###### import for seq2seq model inferencing #######
from .seq2seq import data as seq2seq_data
from .seq2seq import model as seq2seq
from .seq2seq.configs import DEFINES as DEFINES_seq2seq


###### import for attention_seq2seq model inferencing ######
from .attention_seq2seq import data as attention_seq2seq_data
from .attention_seq2seq import model as attention_seq2seq
from .attention_seq2seq.configs import DEFINES as DEFINES_attention_seq2seq



def index(request):
    chatroom_list = Room.objects.order_by('rank')[:5]
    context = {
        'chatroom_list': chatroom_list
    }
    return render(request, 'chatroom/index.html', context)


def room(request, lm_name):
    chatroom_list = Room.objects.order_by('rank')[:5]

    context = {
        'lm_name': mark_safe(json.dumps(lm_name)),
        'chatroom_list': chatroom_list
    }
    return render(request, 'chatroom/room.html', context)


def detail(request, lm_name):

    return HttpResponse("You're looking at chatroom using %s." % lm_name)


@csrf_exempt
def post_dataset(request, lm_name):

    question = request.POST.get('question', None)
    answer = request.POST.get('answer', None)


    new_dataset = UserInputDataset(question=question, answer=answer)       # save to DB
    new_dataset.save()

    print("success to insert new QA dataset from the user")
    print("Q: " + question + " || A: " + answer)

    data = {
        'is_valid': 1
    }

    return JsonResponse(data)



def message(request, message, lm_name):
    # if lm_name == 'tranformer':
    # if lm_name == 'seq2seq':
    # if lm_name == 'bert':
    #return HttpResponse("answer: %s" % (message))

    if "너" in message and "이름" in message:
        return HttpResponse("%s" % ("제 이름은 diya chat이에요 :)"))


    if lm_name == 'transformer':
        print(lm_name)

        os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
        arg_length = len(sys.argv)

        if (arg_length < 2):
            raise Exception("Don't call us. We'll call you")

        # Construct vocab file
        char2idx, idx2char, vocabulary_length = tranformer_data.load_vocabulary()

        ################# Encoder process #################
        input = message

        print(input)
        predic_input_enc, predic_input_enc_length = tranformer_data.enc_processing([input], char2idx)
        # Since it is not train process, there no input to decoder.
        # "" (empty string) is delivered just for fitting in the fixed structure
        predic_output_dec, predic_output_dec_length = tranformer_data.dec_output_processing([""], char2idx)
        # Since it is not train process, there no output from decoder.
        # "" (empty string) is delivered just for fitting in the fixed structure
        predic_target_dec = tranformer_data.dec_target_processing([""], char2idx)


        # Construct tf estimator
        transformer_classifier = tf.estimator.Estimator(
            model_fn=transformer.Model,
            model_dir=DEFINES_transformer.check_point_path_transformer,
            params={  # Parameter passing to model
                'embedding_size': DEFINES_transformer.embedding_size_transformer,
                'model_hidden_size': DEFINES_transformer.model_hidden_size_transformer,
                'ffn_hidden_size': DEFINES_transformer.ffn_hidden_size_transformer,
                'attention_head_size': DEFINES_transformer.attention_head_size_transformer,
                'learning_rate': DEFINES_transformer.learning_rate_transformer,
                'vocabulary_length': vocabulary_length,
                'embedding_size': DEFINES_transformer.embedding_size_transformer,
                'layer_size': DEFINES_transformer.layer_size_transformer,
                'max_sequence_length': DEFINES_transformer.max_sequence_length_transformer,
                'xavier_initializer': DEFINES_transformer.xavier_initializer_transformer
            })


        answer = ""

        for i in range(25):
            if i > 0:
                predic_output_dec, predic_output_decLength = tranformer_data.dec_output_processing([answer], char2idx)
                predic_target_dec = tranformer_data.dec_target_processing([answer], char2idx)

            ########### Get predicted answer ##########
            predictions = transformer_classifier.predict(
                input_fn=lambda: tranformer_data.eval_input_fn(predic_input_enc, predic_output_dec, predic_target_dec, 1))

            answer, finished = tranformer_data.pred_next_string(predictions, idx2char)

            if finished:
                break

        print("answer: ", answer)



    elif lm_name == 'seq2seq':
        print(lm_name)

        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)
        arg_length = len(sys.argv)

        if(arg_length < 2):
            raise Exception("Don't call us. We'll call you")

        char2idx,  idx2char, vocabulary_length = seq2seq_data.load_vocabulary()
        input = message

        print(input)

        predic_input_enc, predic_input_enc_length = seq2seq_data.enc_processing([
                                                                        input], char2idx)
        predic_output_dec, predic_output_dec_length = seq2seq_data.dec_input_processing([
                                                                                ""], char2idx)
        predic_target_dec = seq2seq_data.dec_target_processing([""], char2idx)

        classifier = tf.estimator.Estimator(
            model_fn=seq2seq.model,
            model_dir=DEFINES_seq2seq.check_point_path_seq2seq,
            params={
                'hidden_size': DEFINES_seq2seq.hidden_size_seq2seq,
                'layer_size': DEFINES_seq2seq.layer_size_seq2seq,
                'learning_rate': DEFINES_seq2seq.learning_rate_seq2seq,
                'vocabulary_length': vocabulary_length,
                'embedding_size': DEFINES_seq2seq.embedding_size_seq2seq,
                'embedding': DEFINES_seq2seq.embedding_seq2seq,
                'multilayer': DEFINES_seq2seq.multilayer_seq2seq,
            })

        predictions = classifier.predict(
            input_fn=lambda: seq2seq_data.eval_input_fn(predic_input_enc, predic_output_dec, predic_target_dec, DEFINES_seq2seq.batch_size_seq2seq))

        answer = seq2seq_data.pred2string(predictions, idx2char)


    elif lm_name == 'attention_seq2seq':
        print(lm_name)

        tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)
        arg_length = len(sys.argv)

        if(arg_length < 2):
            raise Exception("Don't call us. We'll call you")

        char2idx,  idx2char, vocabulary_length = attention_seq2seq_data.load_vocabulary()

        input = message

        print(input)
        predic_input_enc, predic_input_enc_length = attention_seq2seq_data.enc_processing([
                                                                                          input], char2idx)

        predic_target_dec, _ = attention_seq2seq_data.dec_target_processing([
                                                                            ""], char2idx)

        if DEFINES_attention_seq2seq.serving_attention_seq2seq == True:

            predictor_fn = tf.contrib.predictor.from_saved_model(
                export_dir="/home/evo_mind/DeepLearning/NLP/Work/ChatBot2_Final/data_out/model/1541575161"
            )
        else:
            # Construct estimator
            classifier = tf.estimator.Estimator(
                model_fn=attention_seq2seq.Model,
                model_dir=DEFINES_attention_seq2seq.check_point_path_attention_seq2seq,
                params={
                    'hidden_size': DEFINES_attention_seq2seq.hidden_size_attention_seq2seq,
                    'layer_size': DEFINES_attention_seq2seq.layer_size_attention_seq2seq,
                    'learning_rate': DEFINES_attention_seq2seq.learning_rate_attention_seq2seq,
                    'teacher_forcing_rate': DEFINES_attention_seq2seq.teacher_forcing_rate_attention_seq2seq, # 학습시 디코더 인풋 정답 지원율 설정
                    'vocabulary_length': vocabulary_length,
                    'embedding_size': DEFINES_attention_seq2seq.embedding_size_attention_seq2seq,
                    'embedding': DEFINES_attention_seq2seq.embedding_attention_seq2seq,
                    'multilayer': DEFINES_attention_seq2seq.multilayer_attention_seq2seq,
                    'attention': DEFINES_attention_seq2seq.attention_attention_seq2seq,
                    'teacher_forcing': DEFINES_attention_seq2seq.teacher_forcing_attention_seq2seq,
                    'loss_mask': DEFINES_attention_seq2seq.loss_mask_attention_seq2seq, # PAD에 대한 마스크를 통해 loss를 제한
                    'serving': DEFINES_attention_seq2seq.serving_attention_seq2seq
                })

        if DEFINES_attention_seq2seq.serving_attention_seq2seq == True:
            predictions = predictor_fn({'input':predic_input_enc, 'output':predic_target_dec})

        else:
            predictions = classifier.predict(
                input_fn=lambda: attention_seq2seq_data.eval_input_fn(predic_input_enc, predic_target_dec, DEFINES_attention_seq2seq.batch_size_attention_seq2seq))

        # convert indexed sentence into string sentence
        answer = attention_seq2seq_data.pred2string(predictions, idx2char)

diyaChat/chatroom/templates/chatroom/base.html
{% load static %}

<!DOCTYPE html>
<html>

<!--JQuery CDN must be located above the other CDNs (keep the link most recent version)-->
<script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous">
</script>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">          <!--rendering properly in mobile devices-->
    <title>chatroom</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <!--Google font family link-->
    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Lobster|Poor+Story|Sunflower:300&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="../../static/chatroom/css/style.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!--index page superslide-->
    <link rel="stylesheet" type="text/css" href="../static/chatroom/css/superslides.css">
    <script src="../static/chatroom/js/jquery.superslides.min.js"></script>
    <script src="../static/chatroom/js/typed.min.js"></script>
</head>

<body>

    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <a class="siteTitle" href ="{% url 'chatroom:index' %}" style="text-decoration:none;">
                    <span class="logo" role="link" tabindex="0">
                        <img src="../../static/chatroom/img/logo.png">
                    </span>
                </a>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
            </div>
        </header>

        <div class="mdl-layout__drawer">
            <div id="logoNameContainer">
                <a href="{% url 'chatroom:index' %}">
                    <span class="logo" role="link" tabindex="0">
                        <img src="../../static/chatroom/img/logo.png" style="width:200px; margin: 8px;">
                    </span>
                </a>
            </div>
            <nav class="mdl-navigation">

            {% for chatroom in chatroom_list %}
                <a class="mdl-navigation__link" href="/chatroom/{{ chatroom.lm_name }}/" style="text-decoration:none; color:#ffffff;">{{ chatroom.lm_name }}</a>
            {% endfor %}

            </nav>
        </div>


        <main class="mdl-layout__content">

            {% block content %}

            {% endblock content %}

        </main>
    </div>




    <script src="../static/chatroom/js/jquery.superslides.min.js"></script>
    <script src="../static/chatroom/js/typed.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3.0.6/dist/isotope.pkgd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="../static/chatroom/js/script.js"></script>

</body>

</html>

diyaChat/chatroom/templates/chatroom/index.html
{% extends 'chatroom/base.html' %}

{% block content %}

<div id="slides" class="col-md-12">
    <div class="overlay"></div>

    <div class="slides-container">
        <img src="../../static/chatroom/img/slide1.jpg" alt="">
        <img src="../../static/chatroom/img/slide2.jpg" alt="">
        <img src="../../static/chatroom/img/slide3.jpg" alt="">
        <img src="../../static/chatroom/img/slide4.jpg" alt="">
    </div>

    <div class="titleMessage">
        <div class="heading">
        <p class="main">Diya Chat</p>
        <p class="sub typed" style="padding-top:15px;"></p>
        </div>
    </div>

    <nav class="slides-navigation" style="width:100%;">
        <a href="#" class="next" style="right:4%;"></a>
        <a href="#" class="prev" style="left:2%"></a>
    </nav>
</div>


<div class="container mb-5 mt-5">
    <div class="pricing card-deck flex-column flex-md-row mb-3">

        {% if chatroom_list %}

            {% for chatroom in chatroom_list %}

                <div class="card card-pricing text-center px-3 mb-4">
                    <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm model-name">{{ chatroom.lm_name }}</span>
                    <div class="bg-transparent card-header pt-4 border-0">
                        <h1 class="h3 font-weight-normal text-primary text-center mb-0" data-pricing-value="15"><span class="price">{{ chatroom.subtitle }}</span></h1>
                    </div>
                    <div class="card-body pt-0">
                        <ul class="list-unstyled mb-4">
                            <!-- 나중에는 model.py의 Room 모델에 description, loss 등의 field를 추가할 것 -->
                            <li>Description: {{ chatroom.description }}</li>
                            <li>Loss: {{ chatroom.loss }}</li>
                            <li>Rank: {{ chatroom.rank }}</li>
                            <li>Paper link: <a href="{{ chatroom.paper_link }}">{{ chatroom.lm_name }}</a></li>
                            <li>Accuracy: </li>
                        </ul>
                        <a href="/chatroom/{{ chatroom.lm_name }}/">
                            <button type="button" class="btn btn-outline-secondary mb-3">
                                Start Conversation
                            </button>
                        </a>
                    </div>
                </div>

            {% endfor %}

        {% else %}

            <p>No chatroom available</p>

        {% endif %}

    </div>
</div>

<div class="text-muted mt-5 mb-5 text-center small">
    <a class="text-muted" target="_blank" href="https://github.com/kooyunmo/KoreanChatbot">
        <img class="git-logo" src="../../static/chatroom/img/github-logo.png" alt="" style="width:30px; padding:5px;">
        <span>KoreanChatbot github</span>
    </a>
</div>


{% endblock content %}